name: fulltest

on: [ push ]

jobs:
  fulltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3' # The Go version to download (if necessary) and use.
      - name: fulltest
        run: make fulltest
